# render.yaml

services:
  - type: web
    name: trading-signal-app
    # ... (rest of your web service config) ...
    
  # --- ADD THIS NEW SERVICE ---
  - type: cron
    name: data-pipeline-runner
    env: python
    rootDir: trading_signal_app
    plan: free # Or your preferred plan
    # This schedule runs the job every day at 1 AM UTC. Adjust as needed.
    schedule: "0 1 * * *" 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python data_pipeline.py"
